#!/usr/bin/env pwsh
$ErrorActionPreference = "Stop"

$workingDir = Convert-Path .
Write-Host "🚀 ================ OBSOLETE ====================" -ForegroundColor Yellow
Write-Host "🚀 Use `docker-ci` Instead " -ForegroundColor Yellow
Write-Host "🚀 ================ OBSOLETE ====================" -ForegroundColor Yellow
Write-Host "🚀 Running Docker CI: $workingDir"
Write-Host "🧾 Arguments: $args"

& dotnet /nuke/docker/Docker.dll @args

if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Build Failed: $LASTEXITCODE"

    exit $LASTEXITCODE
}