#!/usr/bin/env pwsh
$ErrorActionPreference = "Stop"

$workingDir = Convert-Path .
Write-Host "🚀 Running Docker CI: $workingDir"
Write-Host "🧾 Arguments: $args"

# Verify dotnet is available
if (-not (Get-Command dotnet -ErrorAction SilentlyContinue)) {
    Write-Error "❌ 'dotnet' Not Found in PATH"
    
    exit 127
}

try {
    dotnet /nuke/Docker.dll @args

    exit $LASTEXITCODE
} catch {
    Write-Error "💥 Build Failed: $_"

    exit 1
}