#!/usr/bin/env pwsh

# Set the script root to the directory where this script is located
# since without the .ps1 extension $PSScriptRoot will not be set.
$PSScriptRoot = "/usr/local/bin"

Import-Module (Join-Path $PSScriptRoot 'nuke-helpers.psm1')

$workingDir = Initialize-BuildScript -scriptName "Node-in-Docker Build" -arguments $args

Set-BuildEnvironment -projectDir $workingDir

$args = Add-RootArgument -arguments $args -rootPath $workingDir

# Run both node and docker builds
Invoke-DotNetCommand -dllPath "/nuke/forge/Forge.dll" -arguments (@("--type", "node") + $args)

Invoke-DotNetCommand -dllPath "/nuke/forge/Forge.dll" -arguments (@("--type", "docker") + $args)