#requires -Version 5.1

<#
.SYNOPSIS
    Generates the documentation site home page from the README.

.DESCRIPTION
    README.md owns the project landing text. documentation/src/pages/index.md, the site home page, is
    generated from it so the two cannot drift: the script adds the page front matter and rewrites the
    repository-relative links (design/...) to absolute GitHub links, because the site cannot resolve them.

    Edit README.md, then run this script and commit both files. CI runs it with -Check and fails when
    index.md differs from what the README would generate.

.PARAMETER Check
    Do not write. Exit 1 when documentation/src/pages/index.md is not what the README generates.

.EXAMPLE
    pwsh scripts/sync-site-home.ps1

.EXAMPLE
    pwsh scripts/sync-site-home.ps1 -Check
#>
[CmdletBinding()]
param(
    [switch]$Check
)

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$readmePath = Join-Path $root 'README.md'
$indexPath = Join-Path $root 'documentation/src/pages/index.md'
$repositoryBlobUrl = 'https://github.com/The-Running-Dev/Docker-BuildAgent/blob/main/'

$utf8 = New-Object System.Text.UTF8Encoding($false)

function Read-Lf([string]$path) {
    if (-not (Test-Path -LiteralPath $path)) { return $null }
    return ([System.IO.File]::ReadAllText($path, $utf8) -replace "`r`n", "`n")
}

$readme = Read-Lf $readmePath
if ($null -eq $readme) { throw "README.md not found at $readmePath" }

$body = $readme.Replace('](design/', "]($($repositoryBlobUrl)design/")

$generated = "---`nhide_table_of_contents: false`n---`n`n" +
    "<!-- Generated from README.md by scripts/sync-site-home.ps1. Edit README.md and re-run the script; do not edit this file. -->`n`n" +
    $body

if ($Check) {
    if ((Read-Lf $indexPath) -ne $generated) {
        Write-Error "documentation/src/pages/index.md is out of date. Run: pwsh scripts/sync-site-home.ps1"
        exit 1
    }

    Write-Host 'documentation/src/pages/index.md matches the README.'
    exit 0
}

[System.IO.File]::WriteAllText($indexPath, $generated, $utf8)
Write-Host "Wrote $indexPath"
